package org.hibernate.dialect;

import java.util.Properties;

public class Ingres10Dialect extends Ingres9Dialect {
   public Ingres10Dialect() {
      super();
      this.registerBooleanSupport();
   }

   public String toBooleanValueString(boolean bool) {
      return bool ? "true" : "false";
   }

   protected void registerBooleanSupport() {
      this.registerColumnType(-7, "boolean");
      this.registerColumnType(16, "boolean");
      Properties properties = this.getDefaultProperties();
      String querySubst = properties.getProperty("hibernate.query.substitutions");
      if (querySubst != null) {
         String newQuerySubst = querySubst.replace("true=1,false=0", "");
         properties.setProperty("hibernate.query.substitutions", newQuerySubst);
      }

   }

   public boolean supportsIdentityColumns() {
      return true;
   }

   public boolean hasDataTypeInIdentityColumn() {
      return true;
   }

   public String getIdentitySelectString() {
      return "select last_identity()";
   }

   public String getIdentityColumnString() {
      return "not null generated by default as identity";
   }

   public String getIdentityInsertString() {
      return "default";
   }
}
