#Minecraft server properties
#Tue Mar 21 20:58:33 CST 2017
generator-settings=
allow-nether=true
level-name=world
enable-query=false
allow-flight=false
server-port=25565
level-type=DEFAULT
enable-rcon=true
rcon.port=25575
rcon.password=changeme
force-gamemode=false
level-seed=
server-ip=127.0.0.1
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
texture-pack=
snooper-enabled=true
hardcore=false
online-mode=false
pvp=true
difficulty=3
enable-command-block=false
server-name=EWorld-Survival
gamemode=0
max-players=99
spawn-monsters=true
view-distance=8
generate-structures=true
spawn-protection=4
motd=EWorld-Survival

