package org.hibernate.engine.jdbc.internal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import org.hibernate.AssertionFailure;
import org.hibernate.ScrollMode;
import org.hibernate.cfg.Settings;
import org.hibernate.engine.jdbc.spi.LogicalConnectionImplementor;
import org.hibernate.engine.jdbc.spi.SqlExceptionHelper;
import org.hibernate.engine.jdbc.spi.StatementPreparer;

class StatementPreparerImpl implements StatementPreparer {
   private JdbcCoordinatorImpl jdbcCoordinator;

   StatementPreparerImpl(JdbcCoordinatorImpl jdbcCoordinator) {
      super();
      this.jdbcCoordinator = jdbcCoordinator;
   }

   protected final Settings settings() {
      return this.jdbcCoordinator.sessionFactory().getSettings();
   }

   protected final Connection connectionProxy() {
      return this.logicalConnection().getShareableConnectionProxy();
   }

   protected final LogicalConnectionImplementor logicalConnection() {
      return this.jdbcCoordinator.getLogicalConnection();
   }

   protected final SqlExceptionHelper sqlExceptionHelper() {
      return this.jdbcCoordinator.getTransactionCoordinator().getTransactionContext().getTransactionEnvironment().getJdbcServices().getSqlExceptionHelper();
   }

   public PreparedStatement prepareStatement(String sql) {
      return this.buildPreparedStatementPreparationTemplate(sql, false).prepareStatement();
   }

   public PreparedStatement prepareStatement(String sql, boolean isCallable) {
      this.jdbcCoordinator.executeBatch();
      return this.buildPreparedStatementPreparationTemplate(sql, isCallable).prepareStatement();
   }

   private StatementPreparationTemplate buildPreparedStatementPreparationTemplate(String sql, final boolean isCallable) {
      return new StatementPreparationTemplate(sql) {
         protected PreparedStatement doPrepare() throws SQLException {
            return (PreparedStatement)(isCallable ? StatementPreparerImpl.this.connectionProxy().prepareCall(this.sql) : StatementPreparerImpl.this.connectionProxy().prepareStatement(this.sql));
         }
      };
   }

   private void checkAutoGeneratedKeysSupportEnabled() {
      if (!this.settings().isGetGeneratedKeysEnabled()) {
         throw new AssertionFailure("getGeneratedKeys() support is not enabled");
      }
   }

   public PreparedStatement prepareStatement(String sql, final int autoGeneratedKeys) {
      if (autoGeneratedKeys == 1) {
         this.checkAutoGeneratedKeysSupportEnabled();
      }

      this.jdbcCoordinator.executeBatch();
      return (new StatementPreparationTemplate(sql) {
         public PreparedStatement doPrepare() throws SQLException {
            return StatementPreparerImpl.this.connectionProxy().prepareStatement(this.sql, autoGeneratedKeys);
         }
      }).prepareStatement();
   }

   public PreparedStatement prepareStatement(String sql, final String[] columnNames) {
      this.checkAutoGeneratedKeysSupportEnabled();
      this.jdbcCoordinator.executeBatch();
      return (new StatementPreparationTemplate(sql) {
         public PreparedStatement doPrepare() throws SQLException {
            return StatementPreparerImpl.this.connectionProxy().prepareStatement(this.sql, columnNames);
         }
      }).prepareStatement();
   }

   public PreparedStatement prepareQueryStatement(String sql, final boolean isCallable, final ScrollMode scrollMode) {
      if (scrollMode != null && !scrollMode.equals(ScrollMode.FORWARD_ONLY)) {
         if (!this.settings().isScrollableResultSetsEnabled()) {
            throw new AssertionFailure("scrollable result sets are not enabled");
         } else {
            PreparedStatement ps = (new QueryStatementPreparationTemplate(sql) {
               public PreparedStatement doPrepare() throws SQLException {
                  return (PreparedStatement)(isCallable ? StatementPreparerImpl.this.connectionProxy().prepareCall(this.sql, scrollMode.toResultSetType(), 1007) : StatementPreparerImpl.this.connectionProxy().prepareStatement(this.sql, scrollMode.toResultSetType(), 1007));
               }
            }).prepareStatement();
            this.logicalConnection().getResourceRegistry().registerLastQuery(ps);
            return ps;
         }
      } else {
         PreparedStatement ps = (new QueryStatementPreparationTemplate(sql) {
            public PreparedStatement doPrepare() throws SQLException {
               return (PreparedStatement)(isCallable ? StatementPreparerImpl.this.connectionProxy().prepareCall(this.sql) : StatementPreparerImpl.this.connectionProxy().prepareStatement(this.sql));
            }
         }).prepareStatement();
         this.logicalConnection().getResourceRegistry().registerLastQuery(ps);
         return ps;
      }
   }

   private void setStatementFetchSize(PreparedStatement statement) throws SQLException {
      if (this.settings().getJdbcFetchSize() != null) {
         statement.setFetchSize(this.settings().getJdbcFetchSize());
      }

   }

   private abstract class StatementPreparationTemplate {
      protected final String sql;

      protected StatementPreparationTemplate(String sql) {
         super();
         this.sql = StatementPreparerImpl.this.jdbcCoordinator.getTransactionCoordinator().getTransactionContext().onPrepareStatement(sql);
      }

      public PreparedStatement prepareStatement() {
         try {
            PreparedStatement preparedStatement = this.doPrepare();
            this.setStatementTimeout(preparedStatement);
            this.postProcess(preparedStatement);
            return preparedStatement;
         } catch (SQLException e) {
            throw StatementPreparerImpl.this.sqlExceptionHelper().convert(e, "could not prepare statement", this.sql);
         }
      }

      protected abstract PreparedStatement doPrepare() throws SQLException;

      public void postProcess(PreparedStatement preparedStatement) throws SQLException {
      }

      private void setStatementTimeout(PreparedStatement preparedStatement) throws SQLException {
         int remainingTransactionTimeOutPeriod = StatementPreparerImpl.this.jdbcCoordinator.determineRemainingTransactionTimeOutPeriod();
         if (remainingTransactionTimeOutPeriod > 0) {
            preparedStatement.setQueryTimeout(remainingTransactionTimeOutPeriod);
         }

      }
   }

   private abstract class QueryStatementPreparationTemplate extends StatementPreparationTemplate {
      protected QueryStatementPreparationTemplate(String sql) {
         super(sql);
      }

      public void postProcess(PreparedStatement preparedStatement) throws SQLException {
         super.postProcess(preparedStatement);
         StatementPreparerImpl.this.setStatementFetchSize(preparedStatement);
      }
   }
}
