package fr.neatmonster.nocheatplus.config;

import fr.neatmonster.nocheatplus.actions.AbstractActionFactory;
import fr.neatmonster.nocheatplus.actions.ActionFactory;
import fr.neatmonster.nocheatplus.logging.LogUtil;
import java.io.File;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.bukkit.configuration.MemoryConfiguration;
import org.bukkit.plugin.Plugin;

public class ConfigManager {
   private static ActionFactoryFactory actionFactoryFactory = new ActionFactoryFactory() {
      public final ActionFactory newActionFactory(Map library) {
         return new ActionFactory(library);
      }
   };
   private static final Map worldsMap = new HashMap();
   private static final WorldConfigProvider worldConfigProvider = new WorldConfigProvider() {
      public ConfigFile getDefaultConfig() {
         return ConfigManager.getConfigFile();
      }

      public ConfigFile getConfig(String worldName) {
         return ConfigManager.getConfigFile(worldName);
      }

      public Collection getAllConfigs() {
         return ConfigManager.worldsMap.values();
      }
   };

   public ConfigManager() {
      super();
   }

   public static ActionFactory getActionFactory(Map library) {
      return actionFactoryFactory.newActionFactory(library);
   }

   public static void setActionFactoryFactory(ActionFactoryFactory factory) {
      if (factory != null) {
         actionFactoryFactory = factory;
      } else {
         actionFactoryFactory = new ActionFactoryFactory() {
            public final ActionFactory newActionFactory(Map library) {
               return new ActionFactory(library);
            }
         };
      }

      for(ConfigFile config : worldsMap.values()) {
         config.setActionFactory((AbstractActionFactory)null);
      }

   }

   public static ActionFactoryFactory getActionFactoryFactory() {
      return actionFactoryFactory;
   }

   public static void setAllActionFactories() {
      for(ConfigFile config : worldsMap.values()) {
         config.setActionFactory();
      }

   }

   public static WorldConfigProvider getWorldConfigProvider() {
      return worldConfigProvider;
   }

   public static void cleanup() {
      setActionFactoryFactory((ActionFactoryFactory)null);
   }

   public static ConfigFile getConfigFile() {
      return (ConfigFile)worldsMap.get((Object)null);
   }

   public static synchronized ConfigFile getConfigFileSync() {
      return getConfigFile();
   }

   public static ConfigFile getConfigFile(String worldName) {
      ConfigFile configFile = (ConfigFile)worldsMap.get(worldName);
      if (configFile != null) {
         return configFile;
      } else {
         synchronized(ConfigManager.class) {
            if (worldsMap.containsKey(worldName)) {
               return (ConfigFile)worldsMap.get(worldName);
            } else {
               ConfigFile globalConfig = getConfigFile();
               worldsMap.put(worldName, globalConfig);
               return globalConfig;
            }
         }
      }
   }

   public static synchronized ConfigFile getConfigFileSync(String worldName) {
      return getConfigFile(worldName);
   }

   public static synchronized void init(Plugin plugin) {
      worldsMap.clear();
      File globalFile = new File(plugin.getDataFolder(), "config.yml");
      PathUtils.processPaths(globalFile, "global config", false);
      ConfigFile globalConfig = new ConfigFile();
      globalConfig.setDefaults(new DefaultConfig());
      globalConfig.options().copyDefaults(true);
      if (globalFile.exists()) {
         try {
            globalConfig.load(globalFile);

            try {
               if (globalConfig.getBoolean("savebackconfig")) {
                  if (!globalConfig.contains("configversion.created")) {
                     globalConfig.set("configversion.created", 632);
                  }

                  globalConfig.set("configversion.saved", 632);
                  globalConfig.save(globalFile);
               }
            } catch (Exception e) {
               LogUtil.logSevere("[NoCheatPlus] Could not save back config.yml (see exception below).");
               LogUtil.logSevere((Throwable)e);
            }
         } catch (Exception e) {
            LogUtil.logSevere("[NoCheatPlus] Could not load config.yml (see exception below).  Continue with default settings...");
            LogUtil.logSevere((Throwable)e);
         }
      } else {
         globalConfig.options().header("This configuration was auto-generated by NoCheatPlus.");
         globalConfig.options().copyHeader(true);

         try {
            globalConfig.set("configversion.created", 632);
            globalConfig.set("configversion.saved", 632);
            globalConfig.save(globalFile);
         } catch (Exception e) {
            LogUtil.logSevere((Throwable)e);
         }
      }

      worldsMap.put((Object)null, globalConfig);
      MemoryConfiguration worldDefaults = PathUtils.getWorldsDefaultConfig(globalConfig);
      HashMap<String, File> worldFiles = new HashMap();
      if (plugin.getDataFolder().isDirectory()) {
         for(File file : plugin.getDataFolder().listFiles()) {
            if (file.isFile()) {
               String fileName = file.getName();
               if (fileName.matches(".+_config.yml$")) {
                  String worldname = fileName.substring(0, fileName.length() - 11);
                  worldFiles.put(worldname, file);
               }
            }
         }
      }

      for(Map.Entry worldEntry : worldFiles.entrySet()) {
         File worldFile = (File)worldEntry.getValue();
         PathUtils.processPaths(worldFile, "world " + (String)worldEntry.getKey(), true);
         ConfigFile worldConfig = new ConfigFile();
         worldConfig.setDefaults(worldDefaults);
         worldConfig.options().copyDefaults(true);

         try {
            worldConfig.load(worldFile);
            worldsMap.put(worldEntry.getKey(), worldConfig);

            try {
               if (worldConfig.getBoolean("savebackconfig")) {
                  worldConfig.save(worldFile);
               }
            } catch (Exception e) {
               LogUtil.logSevere("[NoCheatPlus] Couldn't save back world-specific configuration for " + (String)worldEntry.getKey() + " (see exception below).");
               LogUtil.logSevere((Throwable)e);
            }
         } catch (Exception e) {
            LogUtil.logSevere("[NoCheatPlus] Couldn't load world-specific configuration for " + (String)worldEntry.getKey() + " (see exception below). Continue with global default settings...");
            LogUtil.logSevere((Throwable)e);
         }

         worldConfig.setDefaults(globalConfig);
         worldConfig.options().copyDefaults(true);
      }

   }

   public static void setForAllConfigs(String path, Object value) {
      for(ConfigFile cfg : worldsMap.values()) {
         cfg.set(path, value);
      }

   }

   public static Double getMaxNumberForAllConfigs(String path) {
      Number max = null;

      for(ConfigFile config : worldsMap.values()) {
         try {
            Object obj = config.get(path);
            if (obj instanceof Number) {
               Number num = (Number)obj;
               if (max == null || num.doubleValue() > max.doubleValue()) {
                  max = num;
               }
            }
         } catch (Throwable var6) {
         }
      }

      return max.doubleValue();
   }

   public static Double getMinNumberForAllConfigs(String path) {
      Number min = null;

      for(ConfigFile config : worldsMap.values()) {
         try {
            Object obj = config.get(path);
            if (obj instanceof Number) {
               Number num = (Number)obj;
               if (min == null || num.doubleValue() < min.doubleValue()) {
                  min = num;
               }
            }
         } catch (Throwable var6) {
         }
      }

      return min.doubleValue();
   }

   public interface ActionFactoryFactory {
      ActionFactory newActionFactory(Map var1);
   }
}
