package fr.neatmonster.nocheatplus.config;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import org.bukkit.Material;

public class DefaultConfig extends ConfigFile {
   public static final int buildNumber = 632;

   public DefaultConfig() {
      super();
      this.set("savebackconfig", true);
      this.set("configversion.notify", true);
      this.set("logging.active", true);
      this.set("logging.debug", false);
      this.set("logging.backend.console.active", true);
      this.set("logging.backend.console.prefix", "[NoCheatPlus] ");
      this.set("logging.backend.file.active", true);
      this.set("logging.backend.file.prefix", "");
      this.set("logging.backend.file.filename", "nocheatplus.log");
      this.set("logging.backend.ingamechat.active", true);
      this.set("logging.backend.ingamechat.prefix", "&cNCP: &f");
      this.set("logging.backend.ingamechat.subscriptions", false);
      this.set("data.expiration.active", false);
      this.set("data.expiration.duration", 60);
      this.set("data.expiration.history", false);
      this.set("data.consistencychecks.active", true);
      this.set("data.consistencychecks.interval", 10);
      this.set("data.consistencychecks.maxtime", 2);
      this.set("data.consistencychecks.suppresswarnings", false);
      this.set("protection.plugins.hide.active", true);
      this.set("protection.plugins.hide.nopermission.message", "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.");
      this.set("protection.plugins.hide.nopermission.commands", Arrays.asList("plugins", "version", "icanhasbukkit"));
      this.set("protection.plugins.hide.unknowncommand.message", "Unknown command. Type \"/help\" for help.");
      this.set("protection.plugins.hide.unknowncommand.commands", new LinkedList());
      this.set("protection.commands.consoleonly.active", false);
      this.set("protection.commands.consoleonly.commands", Arrays.asList("op", "deop"));
      this.set("protection.clients.motd.active", true);
      this.set("protection.clients.motd.allowall", false);
      this.set("checks.blockbreak.direction.active", true);
      this.set("checks.blockbreak.direction.actions", "cancel vl>10 log:bdirection:0:5:if cancel");
      this.set("checks.blockbreak.fastbreak.active", true);
      this.set("checks.blockbreak.fastbreak.strict", true);
      this.set("checks.blockbreak.fastbreak.delay", 90);
      this.set("checks.blockbreak.fastbreak.intervalsurvival", 100);
      this.set("checks.blockbreak.fastbreak.grace", 2000);
      this.set("checks.blockbreak.fastbreak.actions", "cancel vl>0 log:fastbreak:3:5:cif cancel");
      this.set("checks.blockbreak.frequency.active", true);
      this.set("checks.blockbreak.frequency.intervalcreative", 95);
      this.set("checks.blockbreak.frequency.intervalsurvival", 45);
      this.set("checks.blockbreak.frequency.shortterm.ticks", 5);
      this.set("checks.blockbreak.frequency.shortterm.limit", 7);
      this.set("checks.blockbreak.frequency.actions", "cancel vl>5 log:bbfrequency:3:5:if cancel vl>60 log:bbfrequency:0:5:cif cancel cmd:kickfrequency");
      this.set("checks.blockbreak.noswing.active", true);
      this.set("checks.blockbreak.noswing.actions", "cancel vl>10 log:noswing:0:5:if cancel");
      this.set("checks.blockbreak.reach.active", true);
      this.set("checks.blockbreak.reach.actions", "cancel vl>5 log:breach:0:2:if cancel");
      this.set("checks.blockbreak.wrongblock.active", true);
      this.set("checks.blockbreak.wrongblock.level", 10);
      this.set("checks.blockbreak.wrongblock.actions", "cancel vl>10 log:bwrong:0:5:if cancel vl>30 log:bwrong:0:5:cif cancel cmd:kickwb");
      this.set("checks.blockinteract.direction.active", true);
      this.set("checks.blockinteract.direction.actions", "cancel vl>10 log:bdirection:0:3:if cancel");
      this.set("checks.blockinteract.reach.active", true);
      this.set("checks.blockinteract.reach.actions", "cancel vl>5 log:breach:0:2:if cancel");
      this.set("checks.blockinteract.speed.active", true);
      this.set("checks.blockinteract.speed.interval", 2000);
      this.set("checks.blockinteract.speed.limit", 60);
      this.set("checks.blockinteract.speed.actions", "cancel vl>200 log:bspeed:0:2:if cancel vl>1000 cancel log:bspeed:0:2:icf cmd:kickbspeed");
      this.set("checks.blockinteract.visible.active", true);
      this.set("checks.blockinteract.visible.actions", "cancel vl>5 log:bvisible:0:2:if cancel");
      this.set("checks.blockplace.autosign.active", true);
      this.set("checks.blockplace.autosign.actions", "cancel vl>10 log:bautosign:0:3:if cancel");
      this.set("checks.blockplace.direction.active", true);
      this.set("checks.blockplace.direction.actions", "cancel vl>10 log:bdirection:0:3:if cancel");
      this.set("checks.blockplace.fastplace.active", true);
      this.set("checks.blockplace.fastplace.limit", 22);
      this.set("checks.blockplace.fastplace.shortterm.ticks", 10);
      this.set("checks.blockplace.fastplace.shortterm.limit", 6);
      this.set("checks.blockplace.fastplace.actions", "cancel vl>100 log:fastplace:3:5:cif cancel");
      this.set("checks.blockplace.reach.active", true);
      this.set("checks.blockplace.reach.actions", "cancel vl>5 log:breach:0:2:if cancel");
      this.set("checks.blockplace.noswing.active", true);
      this.set("checks.blockplace.noswing.actions", "cancel vl>10 log:noswing:0:5:if cancel");
      this.set("checks.blockplace.speed.active", true);
      this.set("checks.blockplace.speed.interval", 45L);
      this.set("checks.blockplace.speed.actions", "cancel vl>150 log:bpspeed:3:5:if cancel vl>1000 log:bpspeed:3:5:cif cancel");
      this.set("checks.chat.color.active", true);
      this.set("checks.chat.color.actions", "log:color:0:1:if cancel");
      this.set("checks.chat.commands.active", true);
      this.set("checks.chat.commands.exclusions", new ArrayList());
      this.set("checks.chat.commands.handleaschat", Arrays.asList("me"));
      this.set("checks.chat.commands.level", 10);
      this.set("checks.chat.commands.shortterm.ticks", 18);
      this.set("checks.chat.commands.shortterm.level", 3);
      this.set("checks.chat.commands.actions", "log:commands:0:5:cf cancel cmd:kickcommands vl>20 log:commands:0:5:cf cancel cmd:tempkick1");
      this.set("checks.chat.captcha.active", false);
      this.set("checks.chat.captcha.characters", "abcdefghjkmnpqrtuvwxyzABCDEFGHJKMNPQRTUVWXYZ2346789");
      this.set("checks.chat.captcha.length", 6);
      this.set("checks.chat.captcha.question", "&cPlease type '&6[captcha]&c' to continue sending messages/commands.");
      this.set("checks.chat.captcha.success", "&aOK, it sounds like you're not a spambot.");
      this.set("checks.chat.captcha.tries", 3);
      this.set("checks.chat.captcha.actions", "cancel cmd:kickcaptcha vl>4 log:captcha:2:5:cf cancel cmd:kickcaptcha");
      this.set("checks.chat.text.active", true);
      this.set("checks.chat.text.frequency.normal.minimum", (double)0.0F);
      this.set("checks.chat.text.frequency.normal.factor", 0.9);
      this.set("checks.chat.text.frequency.normal.weight", 6);
      this.set("checks.chat.text.frequency.normal.level", 160);
      this.set("checks.chat.text.frequency.normal.actions", "cancel cmd:tellchatnormal vl>7 log:chatnormal:0:5:f cancel cmd:tellchatnormal vl>20 log:chatnormal:0:5:cf cancel cmd:kickchatnormal vl>40 log:chatnormal:0:5:cf cancel cmd:kickchat5");
      this.set("checks.chat.text.frequency.shortterm.minimum", (double)2.0F);
      this.set("checks.chat.text.frequency.shortterm.factor", 0.7);
      this.set("checks.chat.text.frequency.shortterm.weight", (double)3.0F);
      this.set("checks.chat.text.frequency.shortterm.level", (double)20.0F);
      this.set("checks.chat.text.frequency.shortterm.actions", "log:chatfast:0:5:cf cancel cmd:kickchatfast vl>20 log:chatfast:0:5:cf cancel cmd:kickchat1 vl>40 log:chatfast:0:5:cf cancel cmd:kickchat5");
      this.set("checks.chat.text.message.lettercount", (double)1.0F);
      this.set("checks.chat.text.message.partition", (double)1.0F);
      this.set("checks.chat.text.message.uppercase", (double)1.0F);
      this.set("checks.chat.text.message.afterjoin", (double)1.5F);
      this.set("checks.chat.text.message.nomoving", (double)1.5F);
      this.set("checks.chat.text.message.repeatviolation", (double)1.0F);
      this.set("checks.chat.text.message.repeatglobal", (double)1.0F);
      this.set("checks.chat.text.message.repeatself", (double)1.5F);
      this.set("checks.chat.text.message.words.lengthav", (double)1.0F);
      this.set("checks.chat.text.message.words.lengthmsg", (double)1.0F);
      this.set("checks.chat.text.message.words.noletter", (double)0.0F);
      this.set("checks.chat.text.global.active", true);
      this.set("checks.chat.text.global.weight", (double)0.5F);
      this.set("checks.chat.text.global.words.active", false);
      this.set("checks.chat.text.global.weight", (double)1.0F);
      this.set("checks.chat.text.global.prefixes.active", false);
      this.set("checks.chat.text.global.similarity.active", false);
      this.set("checks.chat.text.player.active", true);
      this.set("checks.chat.text.player.words.active", false);
      this.set("checks.chat.text.player.prefixes.active", false);
      this.set("checks.chat.text.player.similarity.active", false);
      this.set("checks.chat.warning.active", true);
      this.set("checks.chat.warning.level", 67);
      this.set("checks.chat.warning.message", "&e>>>\n&e>>> &cPlease &eslow down &cchat, &eyou might get kicked &cfor spam.\n&e>>>");
      this.set("checks.chat.warning.timeout", 10);
      this.set("checks.chat.relog.active", true);
      this.set("checks.chat.relog.timeout", 5000L);
      this.set("checks.chat.relog.warning.message", "&cYou relogged really fast! If you keep doing that, you're going to be banned.");
      this.set("checks.chat.relog.warning.number", 1);
      this.set("checks.chat.relog.kickmessage", "Too fast re-login, try with a little delay.");
      this.set("checks.chat.relog.warning.timeout", 60000L);
      this.set("checks.chat.relog.actions", "log:relog:0:10:cf cancel vl>20 log:relog:0:10:cf cancel cmd:tempkick5");
      this.set("checks.chat.logins.active", true);
      this.set("checks.chat.logins.startupdelay", 600);
      this.set("checks.chat.logins.perworldcount", false);
      this.set("checks.chat.logins.seconds", 10);
      this.set("checks.chat.logins.limit", 10);
      this.set("checks.chat.logins.kickmessage", "Too many people logging in, retry soon.");
      this.set("checks.combined.bedleave.active", true);
      this.set("checks.combined.bedleave.actions", "cancel log:bedleave:0:5:if cmd:kickbedleave");
      this.set("checks.combined.enderpearl.active", true);
      this.set("checks.combined.enderpearl.preventclickblock", true);
      this.set("checks.combined.improbable.active", true);
      this.set("checks.combined.improbable.level", 300);
      this.set("checks.combined.improbable.actions", "cancel log:improbable:2:8:if");
      this.set("checks.combined.invulnerable.active", true);
      this.set("checks.combined.invulnerable.triggers.always", false);
      this.set("checks.combined.invulnerable.triggers.falldistance", true);
      this.set("checks.combined.invulnerable.initialticks.join", -1);
      this.set("checks.combined.invulnerable.ignore", Arrays.asList("FALL"));
      this.set("checks.combined.invulnerable.modifiers.all", 0);
      this.set("checks.combined.munchhausen.active", false);
      this.set("checks.combined.munchhausen.actions", "cancel vl>100 cancel log:munchhausen:0:60:if");
      this.set("checks.combined.yawrate.rate", 380);
      this.set("checks.combined.yawrate.penalty.factor", (double)1.0F);
      this.set("checks.combined.yawrate.penalty.minimum", 250);
      this.set("checks.combined.yawrate.penalty.maximum", 2000);
      this.set("checks.combined.yawrate.improbable", true);
      this.set("checks.fight.canceldead", true);
      this.set("checks.fight.yawrate.active", true);
      this.set("checks.fight.angle.active", true);
      this.set("checks.fight.angle.threshold", 50);
      this.set("checks.fight.angle.actions", "cancel vl>100 log:angle:3:5:f cancel vl>250 log:angle:0:5:cif cancel");
      this.set("checks.fight.critical.active", true);
      this.set("checks.fight.critical.falldistance", 0.01);
      this.set("checks.fight.critical.velocity", 0.1);
      this.set("checks.fight.critical.actions", "cancel vl>50 log:critical:0:5:cif cancel");
      this.set("checks.fight.direction.active", true);
      this.set("checks.fight.direction.strict", true);
      this.set("checks.fight.direction.penalty", 500L);
      this.set("checks.fight.direction.actions", "cancel vl>5 log:fdirection:3:5:f cancel vl>20 log:fdirection:0:5:if cancel vl>50 log:fdirection:0:5:cif cancel");
      this.set("checks.fight.fastheal.active", true);
      this.set("checks.fight.fastheal.interval", 4000L);
      this.set("checks.fight.fastheal.buffer", 1000L);
      this.set("checks.fight.fastheal.actions", "cancel vl>10 cancel log:fastheal:0:10:i vl>30 cancel log:fastheal:0:10:if");
      this.set("checks.fight.godmode.active", true);
      this.set("checks.fight.godmode.minage", 1100);
      this.set("checks.fight.godmode.maxage", 5000);
      this.set("checks.fight.godmode.actions", "log:godmode:2:5:if cancel vl>60 log:godmode:2:5:icf cancel");
      this.set("checks.fight.knockback.active", true);
      this.set("checks.fight.knockback.interval", 50L);
      this.set("checks.fight.knockback.actions", "cancel vl>50 log:knockback:0:5:cif cancel");
      this.set("checks.fight.noswing.active", true);
      this.set("checks.fight.noswing.actions", "cancel vl>10 log:noswing:0:5:if cancel");
      this.set("checks.fight.reach.active", true);
      this.set("checks.fight.reach.survivaldistance", 4.4);
      this.set("checks.fight.reach.penalty", 500);
      this.set("checks.fight.reach.reduce", true);
      this.set("checks.fight.reach.reducedistance", 0.9);
      this.set("checks.fight.reach.reducestep", 0.15);
      this.set("checks.fight.reach.actions", "cancel vl>10 log:freach:2:5:if cancel");
      this.set("checks.fight.selfhit.active", true);
      this.set("checks.fight.selfhit.actions", "log:fselfhit:0:5:if cancel vl>10 log:fselfhit:0:5:icf cancel cmd:kickselfhit");
      this.set("checks.fight.speed.active", true);
      this.set("checks.fight.speed.limit", 15);
      this.set("checks.fight.speed.actions", "log:fspeed:0:5:if cancel");
      this.set("checks.fight.speed.shortterm.ticks", 7);
      this.set("checks.fight.speed.shortterm.limit", 6);
      this.set("checks.inventory.drop.active", true);
      this.set("checks.inventory.drop.limit", 100);
      this.set("checks.inventory.drop.timeframe", 20L);
      this.set("checks.inventory.drop.actions", "log:drop:0:1:cif cancel cmd:dropkick:0:1");
      this.set("checks.inventory.fastclick.active", true);
      this.set("checks.inventory.fastclick.sparecreative", true);
      this.set("checks.inventory.fastclick.tweaks1_5", true);
      this.set("checks.inventory.fastclick.limit.shortterm", 4);
      this.set("checks.inventory.fastclick.limit.normal", 15);
      this.set("checks.inventory.fastclick.actions", "cancel vl>50 log:fastclick:3:5:cif cancel");
      this.set("checks.inventory.instantbow.active", true);
      this.set("checks.inventory.instantbow.strict", true);
      this.set("checks.inventory.instantbow.delay", 130);
      this.set("checks.inventory.instantbow.actions", "cancel vl>15 log:instantbow:2:5:if cancel");
      this.set("checks.inventory.instanteat.active", true);
      this.set("checks.inventory.instanteat.actions", "log:instanteat:2:5:if cancel");
      this.set("checks.inventory.fastconsume.active", true);
      this.set("checks.inventory.fastconsume.duration", 0.7);
      this.set("checks.inventory.fastconsume.whitelist", false);
      this.set("checks.inventory.fastconsume.items", new LinkedList());
      this.set("checks.inventory.fastconsume.actions", "log:fastconsume:2:5:if cancel");
      this.set("checks.inventory.items.active", true);
      this.set("checks.inventory.open.active", true);
      this.set("checks.inventory.open.close", true);
      this.set("checks.inventory.open.cancelother", true);
      this.set("checks.moving.creativefly.active", true);
      this.set("checks.moving.creativefly.ignoreallowflight", false);
      this.set("checks.moving.creativefly.ignorecreative", false);
      this.set("checks.moving.creativefly.horizontalspeed", 100);
      this.set("checks.moving.creativefly.maxheight", 128);
      this.set("checks.moving.creativefly.verticalspeed", 100);
      this.set("checks.moving.creativefly.actions", "log:flyshort:3:5:f cancel vl>100 log:flyshort:0:5:if cancel vl>400 log:flylong:0:5:cif cancel");
      this.set("checks.moving.morepackets.active", true);
      this.set("checks.moving.morepackets.actions", "cancel vl>10 log:morepackets:0:2:if cancel vl>100 log:morepackets:0:2:if cancel cmd:kickpackets");
      this.set("checks.moving.morepacketsvehicle.active", true);
      this.set("checks.moving.morepacketsvehicle.actions", "cancel vl>10 log:morepackets:0:2:if cancel");
      this.set("checks.moving.nofall.active", true);
      this.set("checks.moving.nofall.dealdamage", true);
      this.set("checks.moving.nofall.resetonviolation", false);
      this.set("checks.moving.nofall.resetonteleport", false);
      this.set("checks.moving.nofall.resetonvehicle", true);
      this.set("checks.moving.nofall.anticriticals", true);
      this.set("checks.moving.nofall.actions", "log:nofall:0:5:if cancel vl>30 log:nofall:0:5:icf cancel");
      this.set("checks.moving.passable.active", true);
      this.set("checks.moving.passable.raytracing.active", true);
      this.set("checks.moving.passable.raytracing.blockchangeonly", true);
      this.set("checks.moving.passable.raytracing.vcliponly", true);
      this.set("checks.moving.passable.actions", "cancel vl>10 log:passable:0:5:if cancel vl>50 log:passable:0:5:icf cancel");
      this.set("checks.moving.survivalfly.active", true);
      this.set("checks.moving.survivalfly.extended.vertical-accounting", true);
      this.set("checks.moving.survivalfly.falldamage", true);
      this.set("checks.moving.survivalfly.actions", "log:flyshort:3:10:f cancel vl>100 log:flyshort:0:10:if cancel vl>400 log:flylong:0:5:cif cancel vl>1000 log:flylong:0:5:cif cancel cmd:kickfly");
      this.set("checks.moving.survivalfly.hover.active", true);
      this.set("checks.moving.survivalfly.hover.step", 5);
      this.set("checks.moving.survivalfly.hover.ticks", 85);
      this.set("checks.moving.survivalfly.hover.loginticks", 0);
      this.set("checks.moving.survivalfly.hover.falldamage", true);
      this.set("checks.moving.survivalfly.hover.sfviolation", 500);
      this.set("checks.moving.velocity.graceticks", 20);
      this.set("checks.moving.velocity.activationcounter", 80);
      this.set("checks.moving.velocity.activationticks", 140);
      this.set("checks.moving.velocity.strictinvalidation", true);
      this.set("checks.moving.tempkickillegal", true);
      this.set("checks.moving.loadchunks.join", true);
      this.set("checks.moving.sprintinggrace", (double)2.0F);
      this.set("checks.moving.speedgrace", (double)4.0F);
      String start = "[player] failed [check]: ";
      String end = ". VL [violations].";
      String tell = "ncp tell [player] ";
      this.set("strings.angle", "[player] failed [check]: tried to hit multiple entities at the same time. VL [violations].");
      this.set("strings.ban", "ban [player]");
      this.set("strings.ban-ip", "ban-ip [ip]");
      this.set("strings.bautosign", "[player] failed [check]: failed autosign with [tags]. VL [violations].");
      this.set("strings.bbfrequency", "[player] failed [check]: tried to break too many blocks within time frame. VL [violations].");
      this.set("strings.bdirection", "[player] failed [check]: tried to interact with a block out of his line of sight. VL [violations].");
      this.set("strings.bedleave", "[player] failed [check]: sends bed leave packets (was not in bed). VL [violations].");
      this.set("strings.bpspeed", "[player] failed [check]: tried to throw projectiles too quickly. VL [violations].");
      this.set("strings.breach", "[player] failed [check]: exceeds block-interact distance ([reachdistance]). VL [violations].");
      this.set("strings.bspeed", "[player] failed [check]: interacts too fast. VL [violations].");
      this.set("strings.bvisible", "[player] failed [check]: interacts with a block out of sight. VL [violations].");
      this.set("strings.bwrong", "[player] failed [check]: broke another block than clicked. VL [violations].");
      this.set("strings.captcha", "[player] failed captcha repeatedly. VL [violations].");
      this.set("strings.color", "[player] failed [check]: sent colored chat message. VL [violations].");
      this.set("strings.commands", "[player] failed [check]: issued too many commands. VL [violations].");
      this.set("strings.combspeed", "[player] failed [check]: performs different actions at very high speed. VL [violations].");
      this.set("strings.critical", "[player] failed [check]: tried to do a critical hit but wasn't technically jumping [tags]. VL [violations].");
      this.set("strings.drop", "[player] failed [check]: tried to drop more items than allowed. VL [violations].");
      this.set("strings.dropkick", "ncp delay ncp kick [player] Dropping items too fast.");
      this.set("strings.fastbreak", "[player] failed [check]: tried to break blocks ([blockid]) faster than possible. VL [violations].");
      this.set("strings.fastclick", "[player] failed [check]: tried to move items in his inventory too quickly. VL [violations].");
      this.set("strings.fastconsume", "[player] failed [check]: consumes [food] [tags] too fast. VL [violations].");
      this.set("strings.fastheal", "[player] failed [check]: regenerates health faster than usual. VL [violations].");
      this.set("strings.fastplace", "[player] failed [check]: tried to place too many blocks. VL [violations].");
      this.set("strings.fdirection", "[player] failed [check]: tried to hit an entity out of line of sight. VL [violations].");
      this.set("strings.flyshort", "[player] failed [check]: tried to move unexpectedly. VL [violations].");
      this.set("strings.flylong", "[player] failed [check]: tried to move from [locationfrom] to [locationto] over a distance of [distance] block(s). VL [violations].");
      this.set("strings.freach", "[player] failed [check]: tried to attack entity out of reach. VL [violations].");
      this.set("strings.fselfhit", "[player] failed [check]: tried to self-hit. VL [violations].");
      this.set("strings.fspeed", "[player] failed [check]: tried to attack with too high a frequency. VL [violations].");
      this.set("strings.chatnormal", "[player] failed [check]: potentially annoying chat. VL [violations].");
      this.set("strings.godmode", "[player] failed [check]: avoided taking damage or lagging. VL [violations].");
      this.set("strings.improbable", "[player] failed [check]: meets the improbable more than expected. VL [violations].");
      this.set("strings.instantbow", "[player] failed [check]: fires bow too fast. VL [violations].");
      this.set("strings.instanteat", "[player] failed [check]: eats food [food] too fast. VL [violations].");
      this.set("strings.kick", "kick [player]");
      this.set("strings.kickbedleave", "ncp delay ncp kick [player] Go find a bed!");
      this.set("strings.kickbspeed", "ncp kick [player] You interacted too fast!");
      this.set("strings.kickcaptcha", "ncp kick [player] Enter the captcha!");
      this.set("strings.kickchat1", "ncp tempkick [player] 1 You're still not allowed to spam!");
      this.set("strings.kickchat5", "ncp tempkick [player] 5 You're not intended to spam!");
      this.set("strings.kickchatfast", "ncp kick [player] You're not allowed to spam in chat!");
      this.set("strings.kickchatnormal", "ncp kick [player] Too many chat messages, take a break.");
      this.set("strings.kickfly", "ncp delay ncp kick [player] Kicked for flying (or related)");
      this.set("strings.kickcommands", "ncp tempkick [player] 1 You're not allowed to spam commands!");
      this.set("strings.kickfrequency", "ncp kick [player] You did something too fast!");
      this.set("strings.kickgod", "ncp kick [player] God mode?");
      this.set("strings.kickpackets", "ncp delay ncp kick [player] Too many packets (extreme lag?)");
      this.set("strings.kickselfhit", "ncp kick [player] You tried to hit yourself!");
      this.set("strings.kickwb", "ncp kick [player] Block breaking out of sync!");
      this.set("strings.knockback", "[player] failed [check]: tried to do a knockback but wasn't technically sprinting. VL [violations].");
      this.set("strings.morepackets", "[player] failed [check]: sent [packets] more packet(s) than expected. VL [violations].");
      this.set("strings.munchhausen", "[player] failed [check]: almost made it off the pit. VL [violations].");
      this.set("strings.nofall", "[player] failed [check]: tried to avoid fall damage. VL [violations].");
      this.set("strings.chatfast", "[player] failed [check]: acted like spamming (IP: [ip]). VL [violations].");
      this.set("strings.noswing", "[player] failed [check]: didn't swing arm. VL [violations].");
      this.set("strings.passable", "[player] failed [check]: moved into a block ([blockid]). VL [violations].");
      this.set("strings.relog", "[player] failed [check]: relogs too fast. VL [violations].");
      this.set("strings.tellchatnormal", "ncp tell [player] &cNCP: &eToo many messages, slow down...");
      this.set("strings.tempkick1", "ncp tempkick [player] 1 Wait a minute!");
      this.set("strings.tempkick5", "ncp tempkick [player] 5 You have five minutes to think about it!");
      this.set("compatibility.managelisteners", false);
      this.set("compatibility.bukkitapionly", false);
      this.set("compatibility.blocks.ignorepassable", Arrays.asList(Material.WOODEN_DOOR.name(), Material.IRON_DOOR_BLOCK.name(), Material.TRAP_DOOR.name(), Material.PISTON_EXTENSION.name(), Material.PISTON_MOVING_PIECE.name()));
      this.set("compatibility.blocks.allowinstantbreak", new LinkedList());
      this.set("compatibility.blocks.overrideflags.snow", "default");
   }
}
